language: php
php:
- '7.2'
env:
  - SERVER_TEST=http://localhost IPEER_DB_NAME=ipeer_test IPEER_DB_USER=root IPEER_DB_PASSWORD=""

services:
- mysql
install:
- composer install
before_script:
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # install oauth extension
  - pecl install -f oauth-2.0.2
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)/app/webroot?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart
  # setup mysql
  - mysql -e "create database IF NOT EXISTS ipeer_test;" -uroot

script: vendor/bin/phing build-ci
#deploy:
#  provider: releases
#  skip_cleanup: true
#  api_key:
#    secure: JqPtCTP6y1zJqmtShDvvQOSsQ/Vf5iAmk4wfIuw2ATV2puQH7/ojQNmLRb7b59Ek5dJzHzIx3RmK+JZtAPHV7HHEZ4sH0qhEM4GZQjmWre4fqmYS5+XnFjQ7C0iLYmVCklAQ3ziinzzESwrfVxtehq5/XNnt6kUCJorRvS22ee8=
#  file: ipeer-release.zip
#  on:
#    repo: ubc/iPeer
#    tags: true
#    php: 5.3
