services:
  php-saml-app:
    build: .
    env_file: .env
    ports:
      - "8800:80"
    volumes:
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
      - ./index.php:/var/www/html/index.php
      - ./config:/var/www/html/config
      - ./public:/var/www/html/public
