apiVersion: v1
kind: Pod
metadata:
  name: php-saml-app
  namespace: onelogin-saml2
spec:
  containers:
    - name: php-saml-app
      image: my-repo/php-saml-app:v1.0  # Make sure this points to the correct image
      ports:
        - containerPort: 80
